"""Give persistent playlist and history rows database-generated identifiers."""

from __future__ import annotations

from alembic import op

revision = "0002_playlist_identity"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                  FROM pg_attrdef AS definition
                  JOIN pg_attribute AS attribute
                    ON attribute.attrelid = definition.adrelid
                   AND attribute.attnum = definition.adnum
                 WHERE definition.adrelid = 'playlists'::regclass
                   AND attribute.attname = 'id'
            ) THEN
                ALTER TABLE playlists
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                  FROM pg_attrdef AS definition
                  JOIN pg_attribute AS attribute
                    ON attribute.attrelid = definition.adrelid
                   AND attribute.attnum = definition.adnum
                 WHERE definition.adrelid = 'play_history'::regclass
                   AND attribute.attname = 'id'
            ) THEN
                ALTER TABLE play_history
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE play_history ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )
    op.execute("ALTER TABLE playlists ALTER COLUMN id DROP IDENTITY IF EXISTS")
